export const menuChile = [
  {
    to: "/Inicio",
    imgSrc: "/global/icons/Inicio.svg",
    alt: "inicio",
    text: "Inicio",
    dropdown: false,
  },
  {
    to: "/SoyNuevo",
    imgSrc: "/global/icons/perfil.svg",
    alt: "soy-nuevo",
    text: "Soy Nuev@",
    dropdown: false,
  },
  {
    to: "/AgendaColaborador",
    imgSrc: "/global/icons/Agenda.svg",
    alt: "agenda-colaborador",
    text: "Agenda Colaborador",
    dropdown: false,
  },
  {
    to: "/Feriado",
    imgSrc: "/global/icons/Eventos.svg",
    alt: "feriados-chile-perú",
    text: "Feriados Chile - Perú",
    dropdown: false,
  },
  {
    to: "/entelactive",
    imgSrc: "/global/icons/ClubEntel.svg",
    alt: "beneficios",
    text: "e) Active - Beneficios",
    dropdown: false,
  },
  {
    to: "/ServicioCliente",
    imgSrc: "/global/icons/Laptop.svg",
    alt: "serv-al-cliente-interno",
    text: "Serv.al Cliente Interno",
    dropdown: false,
  },
  {
    to: "/portalLiderEntel",
    imgSrc: "/global/icons/PortalLiderEntel.svg",
    alt: "portal-lider-entel",
    text: "Portal Lider Entel",
    dropdown: false,
  },
  {
    to: "",
    imgSrc: "/global/icons/Comunidad.svg",
    alt: "acerca-de-entel",
    text: "Acerca de Entel",
    dropdown: true,
    dropdownItems: [
      { to: "/NuestraCultura", text: "Nuestra Cultura" },
      { to: "/Diversidad", text: "Diversidad, Equidad e Inclusión" },
      { to: "/Etica", text: "Ética y Cumplimiento" },
      { to: "/Biblioteca", text: "Biblioteca Entel" },
      { to: "/ProcesoRenuncia", text: "Proceso de Renuncia" },
      { to: "/Agilidad", text: "Agilidad y gestión de cambio" },
    ],
  }, 
  {
    to: "",
    imgSrc: "/global/icons/ico_plataformas.svg",
    alt: "plataformas",
    text: "Plataformas",
    dropdown: true,
    dropdownItems: [
      { to: "/Nominaciones", text: "Reconocimientos" },
      { to: "/Zoom", text: "Zoom" },
      { to: "/Office365", text: "Office 365" },
      { to: "/Workplace", text: "Workplace" },
      { to: "/UEntel", text: "Universidad Entel" },
    ],
  },
  {
    to: "/Contacto",
    imgSrc: "/global/icons/Ejecutivo.svg",
    alt: "contactos",
    text: "Contactos",
    dropdown: false,
  }
];

export const menuPeru = [
  {
    to: "/Inicio",
    imgSrc: "/global/icons/Inicio.svg",
    alt: "inicio",
    text: "Inicio",
    dropdown: false,
  },
  {
    to: "/SoyNuevo",
    imgSrc: "/global/icons/perfil.svg",
    alt: "soy-nuevo",
    text: "Soy Nuev@",
    dropdown: false,
  },
  {
    to: "/AgendaColaborador",
    imgSrc: "/global/icons/Agenda.svg",
    alt: "agenda-colaborador",
    text: "Agenda Colaborador",
    dropdown: false,
  },
  {
    to: "/Feriado",
    imgSrc: "/global/icons/Eventos.svg",
    alt: "feriados-chile-perú",
    text: "Feriados Chile - Perú",
    dropdown: false,
  },
  {
    to: "/entelactive",
    imgSrc: "/global/icons/ClubEntel.svg",
    alt: "beneficios",
    text: "e) Active - Beneficios",
    dropdown: false,
  },
  {
    to: "/ServicioCliente",
    imgSrc: "/global/icons/Laptop.svg",
    alt: "serv-al-cliente-interno",
    text: "Serv. al Cliente Interno",
    dropdown: false,
  },
  {
    to: "/portalLiderEntel",
    imgSrc: "/global/icons/PortalLiderEntel.svg",
    alt: "portal-lider-entel",
    text: "Portal Lider Entel",
    dropdown: false,
  },
  {
    to: "",
    imgSrc: "/global/icons/Comunidad.svg",
    alt: "acerca-de-entel",
    text: "Acerca de Entel",
    dropdown: true,
    dropdownItems: [
      { to: "/EmbajadorEntel", text: "Embajador Entel" },
      { to: "/NuestraCultura", text: "Nuestra Cultura" },
      { to: "/Diversidad", text: "Diversidad, Equidad e Inclusión" },
      { to: "/Politicas", text: "Políticas" },
      { to: "/Etica", text: "Ética y Cumplimiento" },
      { to: "/NuestrosLideres", text: "Nuestros Líderes" },
      { to: "/Fenomenodelnino", text: "Fenómeno del niño" },
      { to: "/Sostenibilidad", text: "Sostenibilidad" },
      { to: "/ProcesoRenuncia", text: "Proceso de Renuncia" },
      { to: "/Agilidad", text: "Agilidad y gestión de cambio" },
    ],
  }, 
  {
    to: "",
    imgSrc: "/global/icons/ico_plataformas.svg",
    alt: "plataformas",
    text: "Plataformas",
    dropdown: true,
    dropdownItems: [
      { to: "/", text: "Reconocimientos" },
      { to: "/Campus", text: "Universidad Entel" },
      { to: "/Succes", text: "Success Factors" },
      { to: "/EntelFlexOffice", text: "Entel Flex Office" },
      { to: "/Workplace", text: "Workplace" },
      { to: "/", text: "Ausentismo" },
      { to: "/Manual", text: "Manuales" },
      { to: "/Office365", text: "Office 365" },
      { to: "/Enlaces", text: "Enlaces" },
    ],
  },
  {
    to: "/Contacto",
    imgSrc: "/global/icons/Ejecutivo.svg",
    alt: "contactos",
    text: "Contactos",
    dropdown: false,
  },
  {
    to: "/Pregunta",
    imgSrc: "/global/icons/Preguntas.svg",
    alt: "preguntas-frecuentes",
    text: "Preguntas Frecuentes",
    dropdown: false,
  },
  {
    to: "",
    imgSrc: "/global/icons/Internacional.svg",
    alt: "sitios-de-interés",
    text: "Sitios de interés",
    dropdown: true,
    dropdownItems: [],
  },
];